// This defines an array of manufacturer types.
export const manufacturerTypes = [
    'B & M',
    'Vekoma',
    'Intamin',
    'GCI',
    'Zierer',
    'Gerstlauer',
    'Schwarzkopf',
    'Maurer',
    'Zamperla',
    'Pinfari',
    'Soquet',
    'Interlink',
    'SBF Visa',
    'Arrow',
    'Mack',
    'Charles Paige',
    'Strickland',
    'Reverchon',
    'Fabbri',
    'Meridian',
    'Garmendale',
    'DPV Rides',
    'SuperCar',
    'A R M Rides',
    'Big Apple Wacky Worm',
    'WGH',
    'L&T Systems',
    'EOS',
    'Cavazza Diego',
    'Valdemar Lebech',
    'Vernon Keenan',
    'John Henry Lles',
    'CCI',
    'Guvan',
    'Roller Coaster Corporation of America',
    'Horace Cole',
    'RMC',
  ];
