
export const themeParks = [
    'Southend Adventure Island',
    'American Adventure',
    'Alton Towers Resort',
    'Adventure Wonderland',
    'Babylon Park',
    'The Big Sheep',
    'Billing Aquadrome',
    'Blackgang Chine',
    'Blackpool Pleasure Beach',
    'Bottons Pleasure Beach',
    'Brean Leisure Park',
    'Brent Beach',
    'Camel Creek Adventure Park',
    'Chessington World of Adventures',
    'Clacton',
    'Clarence Pier',
    'Cleethorpes',
    'Codonas Amusement Park',
    'Coney Beach Pleasure Park',
    'Crealy Great Adventure Parks',
    'Currys Fun Park Portrush',
    'Diggerland',
    'Dingles Fairground Heritage Centre',
    'Drayton Manor Theme Park',
    'Dreamland Margate',
    'Fantasy Island',
    'Flambards Theme Park',
    'Flamingo Land Resort',
    'Funland',
    'Great Yarmouth Pleasure Beach',
    'Gullivers Kingdom',
    'Gullivers Land',
    'Gullivers Valley',
    'Gullivers World',
    'Hayling Island',
    'Harbour Park',
    'Hemsby',
    'Hidden Valley Discovery Park',
    'Hollycombe Steam Collection',
    'Hunstanton',
    'Joyland',
    'Landmark Forest Adventure Park',
    'Legoland Windsor',
    'Lightwater Valley',
    'M&Ds, Scotlands Theme Park',
    'The Milky Way (amusement park)',
    'New Brighton, Liverpool',
    'Oakwood Theme Park',
    'Paultons Family Theme Park',
    'Pettitts',
    'Pirates Cove, Shanklin',
    'Pleasurewood Hills (East Anglia)',
    'Robin Hill',
    'Southport Pleasureland',
    'Thorpe Park',
    'Twinlakes Theme Park',
    'Yarmouth Pleasure Beach',
    'West Midland Safari Park',
    'Wheelgate Park',
    'Wicksteed Park',
    'Woodlands Family Theme Park',
    'The American Adventure',
    'Camelot Theme Park',
    'Winter Wonderland',
    'Frontierland Family Theme Park',
    'Loudoun Castle',
    'Pleasure Island Theme Park',
    'Djurs Sommerland, Nimtofte',
    'Fårup Sommerland, Saltum',    
    'Karolinelund, Aalborg (closed in 2010)',
    'Legoland Billund, Billund',
    'Rømø Lege- & Hesteland, Rømø',
    'Tivoli Friheden, Århus',
    'Universe, Nordborg',
    'Varde Sommerland, Varde (closed in 2002)',
    'BonBon-Land, Holme-Olstrup',
    'Dyrehavsbakken, Klampenborg',
    'Marielyst Familiepark & Aqualand, Marielyst',
    'Sommerpark, Græsted (closed in 2009)',
    'Sommerland Sjælland, Nykøbing',
    'Tivoli Gardens, Copenhagen',
    'Mariepark, Mariehamn, Åland',
    'Nokkakivi, Lievestuore, Laukaa, Central Finland',
    'PowerPark, Alahärmä, Kauhava, South Ostrobothnia',
    'Puuhamaa, Tervakoski, Janakkala, Tavastia Proper',
    'Visulahti, Mikkeli, South Savonia',
    'Wasalandia, Vaasa, Ostrobothnia (Closed in 2015)',
    'Linnanmäki, Helsinki',
    'Planet FunFun (aka: Fanfaari), Kerava',
    'Kymenlaakso',
    'Tykkimäki, Kouvola',
    'Moomin World, Naantali, Southwest Finland',
    'Särkänniemi (aka: Neulas amusement), Tampere, Pirkanmaa',
    'Bellewaerde (aka: Safari Bellewaerde, Toeristisch Centrum Bellewaerde), Ypres',
    'Bobbejaanland, Lichtaart',
    'Boudewijn Seapark (aka: Dolfinarium Brugge, Boudewijnpark), Bruges',
    'Circus Bruul, Geel',
    'Plopsa Indoor Hasselt, Hasselt',
    'Plopsaland (aka: Meli Park), Adinkerke, De Panne',
    'Plopsaqua De Panne, Adinkerke, De Panne',
    'Plopsa Station, Antwerp',
    'ZoetWaterPark (aka: Zoete Waters), Oud-Heverlee, Flemish Brabant',
    'Euro Space Center, Transinne, province of Luxembourg',
    'Plopsa Coo (aka: TéléCoo), Stavelot, province of Liège',
    'Walibi Belgium (former Six Flags), Wavre, Walloon Brabant',
    'Hirschalm, Unterweißenbach, Upper Austria (Hirschalm Fairytale Hunting Park)',
    'Märchenpark Neusiedlersee, St. Margarethen, Burgenland (Neusiedlersee Family Park)',
    'Wiener Prater, Vienna (Wiener Prater amusement park)',
    'Europark, Vias, Occitanie',
    'Futuroscope, Poitiers, Poitou-Charentes',
    'Napoleonland, Montereau-Fault-Yonne',
    'Nigloland, Dolancourt, Champagne-Ardenne',
    'OK Corral, Cuges-les-Pins',
    'Cigoland, Kintzheim',
    'DidiLand (aka: Fantasialand), Morsbronn-les-Bains',
    'Kid Parc, Gujan Mestras',
    'Walibi Aquitaine, Rocquefort',
    'Le Pal, Dompierre Sur Bresbe',
    'Parc Fenestre, La Bourboule',
    'Vulcania, Saint-Ours-les-Roches',
    'Cobac Parc, Lanhélin',
    'La Récré des 3 Curés, Milizac',
    'Florida Parc, Brochon',
    'Parc Récréatif de la Toison dor, Dijon',
    'Parc Touristique des Combes, Le Creusot',
    'Touro Parc, Romanèche-Thorins',
    'Fami Parc, Nonville',
    'France Miniature, Élancourt',
    'Jardin dAcclimatation, Paris',
    'Mirapolis, Cergy-Pontoise',
    'Disneyland Paris (opened as Euro Disney Resort)',
    'Disneyland Park (opened as Euro Disneyland)',
    'Walt Disney Studios Park',
    'Fraispertuis City, Jeanménil',
    'Walygator Parc ',
    'Festyland, Bretteville-Sur-Odon',
    'Parc Festyland, Caen',
    'Parc du Bocasse, Bocasse',
    'Cité de lespace, Toulouse',
    'Bagatelle, Merlimont',
    'Dennlys Parc, Dennebroeucq',
    'Parc de Lomme, Lomme',
    'Holly Park, Échemiré',
    'Papea City, Le Mans',
    'Puy du Fou, Les Epesses',
    'Mer de Sable, Ermenonville',
    'Parc Astérix, Plailly',
    'Parc Saint Paul, Saint-Paul',
    'Antibes Land, Antibes',
    'Azur Park, St. Tropez',
    'Koaland, Menton',
    'Lunapark Fréjus, Fréjus',
    'Magic Park Land (aka: El Dorado City), Ensuès-la-Redonne',
    'Magic World, Hyères',
    'OK Corral, Cuges-les-Pins',
    'Zygo Park (aka: Zygofolis), Nice',
    'Aérocity Parc, Aubenas',
    'Walibi Rhône-Alpes (aka: Avenir Land), Les Avenières',
    'Gulliver-Welt, Saarbrücken, Saarland',
    'Spree-Park, Berlin',
    'Auto & Technik Museum Sinsheim, Sinsheim',
    'Erlebnispark Tripsdrill, Cleebronn',
    'Europa-Park, Rust',
    'Familien Park, Villingen-Schwenningen',
    'Funny-World, Kappel-Grafenhausen',
    'Ravensburger Spieleland, Meckenbeuren',
    'Schwaben Park, Kaisersbach',
    'Steinwasen Park, Oberried',
    'Tatzmania, Löffingen',
    'Trampoline, Heilbronn',
    'Traumland auf der Bärenhöhle, SonnenbühlBayern Park, Reisbach',
    'Churpfalzpark, Loifling',
    'Erlebnispark Schloss Thurn, Heroldsbach',
    'Fränkisches Wunderland, Plech',
    'Freizeit-Land Geiselwind, Geiselwind',
    'Freizeitpark Ruhpolding, Ruhpolding',
    'Freizeit- und Miniaturpark Allgäu, Weitnau',
    'Legoland Deutschland, Günzburg',
    'Märchen Erlebnispark Marquartstein, Marquartstein',
    'Märchenwald im Isartal, Wolfratshausen',
    'Playmobil FunPark, Zirndorf',
    'Rodel- und Freizeitparadies St. Englmar, Sankt Englmar',
    'Skyline Park, Bad Wörishofen',
    'Sport+Freizeitzentrum Hohenbogen, Neukirchen beim Heiligen Blut',
    'Karls Erlebnis-Dorf Elstal, Wustermark',
    'Erlebnispark Steinau, Steinau an der Straße',
    'Erlebnispark Ziegenhagen, Witzenhausen',
    'Freizeitpark Lochmühle, Wehrheim',
    'Rodelparadies Wasserkuppe, Gersfeld',
    'Salzberger ErlebnisPark, Neuenstein',
    'Taunus Wunderland, Schlangenbad',
    'Wild-und Freizeitpark Willingen, Willingen',
    'Zoo Frankfurt, Frankfurt',
    'Erse-Park, Uetze',
    'Heide Park, Soltau',
    'Jaderpark, Jade',
    'Magic Park Verden, Verden',
    'Nordsee Spielstadt Wangerland, Hohenkirchen',
    'Rasti-Land, Salzhemmendorf',
    'Serengeti Safaripark, Hodenhagen',
    'Tier-und Freizeitpark Thüle, Friesoythe',
    'Wildpark Schwarze Berge, Rosengarten',
    'Rügen Park, Gingst',
    'Affen-und Vogelpark, Reichshof Eckenhagen',
    'Fort Fun Abenteuerland, Bestwig',
    'Freizeitanlage Start und Ziel, Herne',
    'Freizeitzentrum SchiederSee, Delbrück',
    'Hollywood & Safaripark Stukenbrock, Stukenbrock',
    'Panorama Park, Kirchhundem',
    'Phantasialand, Brühl',
    'Potts Park, Minden',
    'Spielerei Rheda-Wiedenbrück, Rheda-Wiedenbrück',
    'Tierpark Nadermann, Schöning',
    'Wunderland Kalkar',
    'Movie Park Germany ',
    'Schloss Beck, Bottrop',
    'Kölner Tivoli',
    'Tobiland',
    'Eifelpark, Gondorf',
    'FreizeitPark Bell, Bell',
    'Holiday Park, Haßloch',
    'Wild-und Freizeitpark Klotten/Cochem, Klotten',
    'Belantis, Leipzig',
    'Freizeitpark Plohn (aka: Erlebnispark Forellenhof Plohn), Lengenfeld',
    'Sonnenlandpark, Lichtenau',
    'Kulturinsel Einsiedel, Zentendorf bei Görlitz',
    'Erlebnistierpark Memleben, Memleben',
    'Erlebniswelt Seilbahnen Thale, Thale',
    'Hansa Park (aka: Hansaland, Legoland Sierksdorf), Sierksdorf',
    'Tolk Schau, Tolk',
    'Märchenwald Saalburg, Saalburg',
    'Emerald Park, Ashbourne, County Meath',
    'Safari Park, Pombia, Piedmont',
    'Felifonte, Castellaneta',
    'zoosafari Fasanolandia, Fasano',
    'Miragica, Molfetta',
    'Edenlandia, Naples',
    'Magic World, Giugliano in Campania',
    'Fiabilandia, Rimini',
    'Mirabilandia, Ravenna',
    'italia in miniatura, Rimini', 
    'Luneur',
    'Lagolandia',
    'Oasi Park',
    'Rainbow Magicland',
    'Zoomarine',
    'Cinecittà World',
    'AdventureLand Borno, Borno',
    'Cowboyland, Voghera',
    'Europark Idroscalo Milano (aka: Luna Euro Park), Segrate',
    'Greenland, Limbiate',
    'Minigolf Adventure, Milano',
    'Leolandia, Capriate San Gervasio',
    'Prehistoric Park, Rivolta',
    'Volandia, Somma Lombardo',
    'Cavallino Matto',
    'Carosello Park, Sottomarina',
    'Gardaland, Castelnuovo del Garda',
    'Movieland Studios (aka: Movie Studios Park)',
    'Playplace, Verona',
    'ToverLand',
    'Efteling',
    'Walibi Holland',
    'de Warbeek',
    'Slagharen',
    'Hellendoorn',
    'Tusenfyrud',
    'Energylandia',
    'ZatorLand',
    'Legendia',
    'Parque de Atracciones de Zaragoza, Zaragoza',
    'Parque de Atracciones Monte Igueldo, San Sebastián',
    'Puy du Fou España, Toledo, Spain',
    'Ferrari Land, Salou',
    'PortAventura Park, Salou and Vilaseca',
    'Tibidabo Amusement Park, Barcelona',
    'Parque de Atracciones de Madrid, Madrid',
    'Parque Warner Madrid, San Martín de la Vega',
    'Sendaviva, Arguedas',
    'DinoPark Algar, Callosa den Sarrià',
    'Pola Park, Santa Pola',
    'Terra Mítica, Benidorm',
    'Furuviksparken, Gävle',
    'Gröna Lund, Stockholm',
    'Kolmården Wildlife Park, Kolmården',
    'Liseberg, Gothenburg',
    'Skara Sommarland, Skara',
    'Santaworld, Mora',
    'Tosselilla Summer Park, Tomelilla',
    'Land of Legends',
    'Ratanga Junction',
    'Gold Reef City, Johannesburg',
    'Luna Park, Coney Island',
    'Disneys Hollywood Studios',
    'Epcot ',
    'Legoland Florida ',
    'Magic Kingdom ',
    'Universal Studios ',
    'Universal Islands of Adventure ',
    'Universal Epic Universe',
    'Busch Gardens Tampa Bay ',
    'Discovery Cove ',
    'Disneys Animal Kingdom ',
    'Gatorland ',
    'Lion Country Safari ',
    'SeaWorld Orlando ',
    'ZooTampa at Lowry Park',
  
];
